//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RuninNotebookAPI.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://foxconn/fbrla/webservice/test", ConfigurationName="ServiceReference1.WebServiceTestSoap")]
    public interface WebServiceTestSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_LOGIN", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Return))]
        RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_LOGIN(string operatorId, string password, string productionLine, string stationGroup, string hostname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_LOGIN", ReplyAction="*")]
        System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_LOGINAsync(string operatorId, string password, string productionLine, string stationGroup, string hostname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_CHECK_STATUS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Return))]
        RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_CHECK_STATUS(string motherBoardSerialNumber, string stationGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_CHECK_STATUS", ReplyAction="*")]
        System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_CHECK_STATUSAsync(string motherBoardSerialNumber, string stationGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_GET_DATA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Return))]
        RuninNotebookAPI.ServiceReference1.ReturnData SFIS_GET_DATA(string motherBoardSerialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_GET_DATA", ReplyAction="*")]
        System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnData> SFIS_GET_DATAAsync(string motherBoardSerialNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_SEND_DATA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Return))]
        RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_SEND_DATA(RuninNotebookAPI.ServiceReference1.DeviceLog deviceLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_SEND_DATA", ReplyAction="*")]
        System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_SEND_DATAAsync(RuninNotebookAPI.ServiceReference1.DeviceLog deviceLog);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_LOGOUT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Return))]
        RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_LOGOUT(string motherBoardSerialNumber, string operatorId, string productionLine, string stationGroup, string hostname, string statusCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_LOGOUT", ReplyAction="*")]
        System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_LOGOUTAsync(string motherBoardSerialNumber, string operatorId, string productionLine, string stationGroup, string hostname, string statusCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_LOGOUT_WEIGHT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Return))]
        RuninNotebookAPI.ServiceReference1.ReturnMotherBoxLabeData SFIS_LOGOUT_WEIGHT(RuninNotebookAPI.ServiceReference1.SendLogoutWeight data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_LOGOUT_WEIGHT", ReplyAction="*")]
        System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnMotherBoxLabeData> SFIS_LOGOUT_WEIGHTAsync(RuninNotebookAPI.ServiceReference1.SendLogoutWeight data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_RESET_MOTHERBOX", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Return))]
        RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_RESET_MOTHERBOX(string motherBoxId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_RESET_MOTHERBOX", ReplyAction="*")]
        System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_RESET_MOTHERBOXAsync(string motherBoxId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_GET_PRINT_DATA", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Return))]
        RuninNotebookAPI.ServiceReference1.ReturnDataPrintResult SFIS_GET_PRINT_DATA(string serialNumber, string groupName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://foxconn/fbrla/webservice/test/SFIS_GET_PRINT_DATA", ReplyAction="*")]
        System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDataPrintResult> SFIS_GET_PRINT_DATAAsync(string serialNumber, string groupName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class ReturnDefault : Return {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnData))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnDefault))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class Return : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class PrintData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class ReturnDataPrintResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string errorMessageField;
        
        private PrintData[] printDataResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public PrintData[] PrintDataResult {
            get {
                return this.printDataResultField;
            }
            set {
                this.printDataResultField = value;
                this.RaisePropertyChanged("PrintDataResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class KeyPair : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class ReturnMotherBoxLabeData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string errorMessageField;
        
        private string skuField;
        
        private int uomField;
        
        private KeyPair[] motherBoxLabelDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("Sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
                this.RaisePropertyChanged("Uom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        public KeyPair[] MotherBoxLabelData {
            get {
                return this.motherBoxLabelDataField;
            }
            set {
                this.motherBoxLabelDataField = value;
                this.RaisePropertyChanged("MotherBoxLabelData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class SendLogoutWeight : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] serialNumberListField;
        
        private string operatorIdField;
        
        private string productionLineField;
        
        private string stationGroupField;
        
        private string hostnameField;
        
        private string statusCodeField;
        
        private string weightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] SerialNumberList {
            get {
                return this.serialNumberListField;
            }
            set {
                this.serialNumberListField = value;
                this.RaisePropertyChanged("SerialNumberList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OperatorId {
            get {
                return this.operatorIdField;
            }
            set {
                this.operatorIdField = value;
                this.RaisePropertyChanged("OperatorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProductionLine {
            get {
                return this.productionLineField;
            }
            set {
                this.productionLineField = value;
                this.RaisePropertyChanged("ProductionLine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string StationGroup {
            get {
                return this.stationGroupField;
            }
            set {
                this.stationGroupField = value;
                this.RaisePropertyChanged("StationGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Hostname {
            get {
                return this.hostnameField;
            }
            set {
                this.hostnameField = value;
                this.RaisePropertyChanged("Hostname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("Weight");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class DeviceLog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string motherBoardSerialNumberField;
        
        private string oSVersionField;
        
        private string googleKeyFileNameField;
        
        private string frontCameraLogField;
        
        private string frontCameraLog2Field;
        
        private string rearCameraLogField;
        
        private string rearCameraLog2Field;
        
        private string hardwareVersionField;
        
        private string ePCField;
        
        private DeviceDetail[] detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MotherBoardSerialNumber {
            get {
                return this.motherBoardSerialNumberField;
            }
            set {
                this.motherBoardSerialNumberField = value;
                this.RaisePropertyChanged("MotherBoardSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OSVersion {
            get {
                return this.oSVersionField;
            }
            set {
                this.oSVersionField = value;
                this.RaisePropertyChanged("OSVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string GoogleKeyFileName {
            get {
                return this.googleKeyFileNameField;
            }
            set {
                this.googleKeyFileNameField = value;
                this.RaisePropertyChanged("GoogleKeyFileName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FrontCameraLog {
            get {
                return this.frontCameraLogField;
            }
            set {
                this.frontCameraLogField = value;
                this.RaisePropertyChanged("FrontCameraLog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FrontCameraLog2 {
            get {
                return this.frontCameraLog2Field;
            }
            set {
                this.frontCameraLog2Field = value;
                this.RaisePropertyChanged("FrontCameraLog2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string RearCameraLog {
            get {
                return this.rearCameraLogField;
            }
            set {
                this.rearCameraLogField = value;
                this.RaisePropertyChanged("RearCameraLog");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string RearCameraLog2 {
            get {
                return this.rearCameraLog2Field;
            }
            set {
                this.rearCameraLog2Field = value;
                this.RaisePropertyChanged("RearCameraLog2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string HardwareVersion {
            get {
                return this.hardwareVersionField;
            }
            set {
                this.hardwareVersionField = value;
                this.RaisePropertyChanged("HardwareVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string EPC {
            get {
                return this.ePCField;
            }
            set {
                this.ePCField = value;
                this.RaisePropertyChanged("EPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        public DeviceDetail[] Details {
            get {
                return this.detailsField;
            }
            set {
                this.detailsField = value;
                this.RaisePropertyChanged("Details");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class DeviceDetail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class Mac : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sequenceField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class DeviceConfiguration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bluetoothMacField;
        
        private string wifiMacField;
        
        private string imei1Field;
        
        private string imei2Field;
        
        private string deviceUnderTestSerialNumberField;
        
        private string colorCodeField;
        
        private string skuField;
        
        private string osVersionField;
        
        private string keyBoxField;
        
        private string googleKeyField;
        
        private string countryCodeField;
        
        private string motherBoardSerialNumberField;
        
        private string customerCodeField;
        
        private string skuFullDescriptionField;
        
        private string packingCodeField;
        
        private string mmiFileField;
        
        private string mediaFileField;
        
        private string apdFileField;
        
        private string apkFileField;
        
        private string adfFileField;
        
        private string modelNameField;
        
        private string cpuSpeedField;
        
        private string ramSizeField;
        
        private string emmcSizeField;
        
        private string testCpuModelField;
        
        private string atTestStationKeyField;
        
        private string hdcpKeyField;
        
        private string qKeyField;
        
        private string testCtsDeviceNameField;
        
        private Mac[] macsField;
        
        private DeviceDetail[] deviceDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BluetoothMac {
            get {
                return this.bluetoothMacField;
            }
            set {
                this.bluetoothMacField = value;
                this.RaisePropertyChanged("BluetoothMac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string WifiMac {
            get {
                return this.wifiMacField;
            }
            set {
                this.wifiMacField = value;
                this.RaisePropertyChanged("WifiMac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Imei1 {
            get {
                return this.imei1Field;
            }
            set {
                this.imei1Field = value;
                this.RaisePropertyChanged("Imei1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Imei2 {
            get {
                return this.imei2Field;
            }
            set {
                this.imei2Field = value;
                this.RaisePropertyChanged("Imei2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string DeviceUnderTestSerialNumber {
            get {
                return this.deviceUnderTestSerialNumberField;
            }
            set {
                this.deviceUnderTestSerialNumberField = value;
                this.RaisePropertyChanged("DeviceUnderTestSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ColorCode {
            get {
                return this.colorCodeField;
            }
            set {
                this.colorCodeField = value;
                this.RaisePropertyChanged("ColorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
                this.RaisePropertyChanged("Sku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string OsVersion {
            get {
                return this.osVersionField;
            }
            set {
                this.osVersionField = value;
                this.RaisePropertyChanged("OsVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string KeyBox {
            get {
                return this.keyBoxField;
            }
            set {
                this.keyBoxField = value;
                this.RaisePropertyChanged("KeyBox");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string GoogleKey {
            get {
                return this.googleKeyField;
            }
            set {
                this.googleKeyField = value;
                this.RaisePropertyChanged("GoogleKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MotherBoardSerialNumber {
            get {
                return this.motherBoardSerialNumberField;
            }
            set {
                this.motherBoardSerialNumberField = value;
                this.RaisePropertyChanged("MotherBoardSerialNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string CustomerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("CustomerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string SkuFullDescription {
            get {
                return this.skuFullDescriptionField;
            }
            set {
                this.skuFullDescriptionField = value;
                this.RaisePropertyChanged("SkuFullDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PackingCode {
            get {
                return this.packingCodeField;
            }
            set {
                this.packingCodeField = value;
                this.RaisePropertyChanged("PackingCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string MmiFile {
            get {
                return this.mmiFileField;
            }
            set {
                this.mmiFileField = value;
                this.RaisePropertyChanged("MmiFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string MediaFile {
            get {
                return this.mediaFileField;
            }
            set {
                this.mediaFileField = value;
                this.RaisePropertyChanged("MediaFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string ApdFile {
            get {
                return this.apdFileField;
            }
            set {
                this.apdFileField = value;
                this.RaisePropertyChanged("ApdFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ApkFile {
            get {
                return this.apkFileField;
            }
            set {
                this.apkFileField = value;
                this.RaisePropertyChanged("ApkFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string AdfFile {
            get {
                return this.adfFileField;
            }
            set {
                this.adfFileField = value;
                this.RaisePropertyChanged("AdfFile");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ModelName {
            get {
                return this.modelNameField;
            }
            set {
                this.modelNameField = value;
                this.RaisePropertyChanged("ModelName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string CpuSpeed {
            get {
                return this.cpuSpeedField;
            }
            set {
                this.cpuSpeedField = value;
                this.RaisePropertyChanged("CpuSpeed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string RamSize {
            get {
                return this.ramSizeField;
            }
            set {
                this.ramSizeField = value;
                this.RaisePropertyChanged("RamSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string EmmcSize {
            get {
                return this.emmcSizeField;
            }
            set {
                this.emmcSizeField = value;
                this.RaisePropertyChanged("EmmcSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string TestCpuModel {
            get {
                return this.testCpuModelField;
            }
            set {
                this.testCpuModelField = value;
                this.RaisePropertyChanged("TestCpuModel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string AtTestStationKey {
            get {
                return this.atTestStationKeyField;
            }
            set {
                this.atTestStationKeyField = value;
                this.RaisePropertyChanged("AtTestStationKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string HdcpKey {
            get {
                return this.hdcpKeyField;
            }
            set {
                this.hdcpKeyField = value;
                this.RaisePropertyChanged("HdcpKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string QKey {
            get {
                return this.qKeyField;
            }
            set {
                this.qKeyField = value;
                this.RaisePropertyChanged("QKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string TestCtsDeviceName {
            get {
                return this.testCtsDeviceNameField;
            }
            set {
                this.testCtsDeviceNameField = value;
                this.RaisePropertyChanged("TestCtsDeviceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=29)]
        public Mac[] Macs {
            get {
                return this.macsField;
            }
            set {
                this.macsField = value;
                this.RaisePropertyChanged("Macs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=30)]
        public DeviceDetail[] DeviceDetails {
            get {
                return this.deviceDetailsField;
            }
            set {
                this.deviceDetailsField = value;
                this.RaisePropertyChanged("DeviceDetails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://foxconn/fbrla/webservice/test")]
    public partial class ReturnData : Return {
        
        private DeviceConfiguration configurationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DeviceConfiguration Configuration {
            get {
                return this.configurationField;
            }
            set {
                this.configurationField = value;
                this.RaisePropertyChanged("Configuration");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceTestSoapChannel : RuninNotebookAPI.ServiceReference1.WebServiceTestSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceTestSoapClient : System.ServiceModel.ClientBase<RuninNotebookAPI.ServiceReference1.WebServiceTestSoap>, RuninNotebookAPI.ServiceReference1.WebServiceTestSoap {
        
        public WebServiceTestSoapClient() {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceTestSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_LOGIN(string operatorId, string password, string productionLine, string stationGroup, string hostname) {
            return base.Channel.SFIS_LOGIN(operatorId, password, productionLine, stationGroup, hostname);
        }
        
        public System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_LOGINAsync(string operatorId, string password, string productionLine, string stationGroup, string hostname) {
            return base.Channel.SFIS_LOGINAsync(operatorId, password, productionLine, stationGroup, hostname);
        }
        
        public RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_CHECK_STATUS(string motherBoardSerialNumber, string stationGroup) {
            return base.Channel.SFIS_CHECK_STATUS(motherBoardSerialNumber, stationGroup);
        }
        
        public System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_CHECK_STATUSAsync(string motherBoardSerialNumber, string stationGroup) {
            return base.Channel.SFIS_CHECK_STATUSAsync(motherBoardSerialNumber, stationGroup);
        }
        
        public RuninNotebookAPI.ServiceReference1.ReturnData SFIS_GET_DATA(string motherBoardSerialNumber) {
            return base.Channel.SFIS_GET_DATA(motherBoardSerialNumber);
        }
        
        public System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnData> SFIS_GET_DATAAsync(string motherBoardSerialNumber) {
            return base.Channel.SFIS_GET_DATAAsync(motherBoardSerialNumber);
        }
        
        public RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_SEND_DATA(RuninNotebookAPI.ServiceReference1.DeviceLog deviceLog) {
            return base.Channel.SFIS_SEND_DATA(deviceLog);
        }
        
        public System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_SEND_DATAAsync(RuninNotebookAPI.ServiceReference1.DeviceLog deviceLog) {
            return base.Channel.SFIS_SEND_DATAAsync(deviceLog);
        }
        
        public RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_LOGOUT(string motherBoardSerialNumber, string operatorId, string productionLine, string stationGroup, string hostname, string statusCode) {
            return base.Channel.SFIS_LOGOUT(motherBoardSerialNumber, operatorId, productionLine, stationGroup, hostname, statusCode);
        }
        
        public System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_LOGOUTAsync(string motherBoardSerialNumber, string operatorId, string productionLine, string stationGroup, string hostname, string statusCode) {
            return base.Channel.SFIS_LOGOUTAsync(motherBoardSerialNumber, operatorId, productionLine, stationGroup, hostname, statusCode);
        }
        
        public RuninNotebookAPI.ServiceReference1.ReturnMotherBoxLabeData SFIS_LOGOUT_WEIGHT(RuninNotebookAPI.ServiceReference1.SendLogoutWeight data) {
            return base.Channel.SFIS_LOGOUT_WEIGHT(data);
        }
        
        public System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnMotherBoxLabeData> SFIS_LOGOUT_WEIGHTAsync(RuninNotebookAPI.ServiceReference1.SendLogoutWeight data) {
            return base.Channel.SFIS_LOGOUT_WEIGHTAsync(data);
        }
        
        public RuninNotebookAPI.ServiceReference1.ReturnDefault SFIS_RESET_MOTHERBOX(string motherBoxId) {
            return base.Channel.SFIS_RESET_MOTHERBOX(motherBoxId);
        }
        
        public System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDefault> SFIS_RESET_MOTHERBOXAsync(string motherBoxId) {
            return base.Channel.SFIS_RESET_MOTHERBOXAsync(motherBoxId);
        }
        
        public RuninNotebookAPI.ServiceReference1.ReturnDataPrintResult SFIS_GET_PRINT_DATA(string serialNumber, string groupName) {
            return base.Channel.SFIS_GET_PRINT_DATA(serialNumber, groupName);
        }
        
        public System.Threading.Tasks.Task<RuninNotebookAPI.ServiceReference1.ReturnDataPrintResult> SFIS_GET_PRINT_DATAAsync(string serialNumber, string groupName) {
            return base.Channel.SFIS_GET_PRINT_DATAAsync(serialNumber, groupName);
        }
    }
}
